### ISSUE TITLE
Add support to use the framework for functional tests in an own typo3 setup 

### ISSUE THREAD

**Issue by zdreicom** [TYPO3/testing-framework#106]
If you have a TYPO3 website which comes with extensions you can not use the framework for functional.

I found to points wey it is not working:

1. typo3/sysext/core/bin/typo3

2. The way how to find the autoload.php is not really fancy it expected to have the typo3 folder on the project root.

**Comment by markuspoerschke** [comment]
I just used the testing framework within a TYPO3 project. It was no problem at all. What are the problems you stumbled over when trying to use it?
