### ISSUE TITLE
ViewHelperBaseTestcase not working for 3rd party extensions in v8

### ISSUE THREAD

**Issue by derhansen** [TYPO3/testing-framework#123]
When using the testing framework v8 for 3rd party extensions, it is not possible to use  `ViewHelperBaseTestcase`, since it uses `\TYPO3\CMS\Fluid\Tests\Unit\Core\Rendering\RenderingContextFixture::class` in `setUp()`. 

In v9 branch, the `RenderingContextFixture` from the `Tests` directory (this fails for 3rd party extensions, since `Tests` are not part of `typo3/minimal`) has been replaced by an own class - see: https://github.com/TYPO3/testing-framework/blob/9/Classes/Fluid/Unit/Core/Rendering/RenderingContextFixture.php

This change should be adopted for v8 too.

**Comment by bmack** [comment]
@derhansen if you need still it, can you create a PR for the respective branches?

**Comment by derhansen** [comment]
I drop support for TYPO3 v8 for my extensions, so I do not need the change any more and close the issue now.
