### ISSUE TITLE
executeFrontendRequest only supports GET method as of now

### ISSUE THREAD

**Issue by sven-carstens** [TYPO3/testing-framework#130]

**Comment by sven-carstens** [comment]
[WIP] on other methods and body content for the request is currently here
https://github.com/sven-carstens/testing-framework/tree/9

**Comment by lolli42** [comment]
Setting this to done with https://github.com/TYPO3/testing-framework/commit/d5cf8536ee837b9d0feec6f2dce132e782cebf01 and https://github.com/TYPO3/testing-framework/commit/28209b6ee189fd7204f168d2dab5a7d0817c0725 being merged.
