### ISSUE TITLE
[BUGFIX] Use correct namespace for WebDriver

### ISSUE THREAD

**Issue by tomasnorre** [TYPO3/testing-framework#172]
Would it be possible to have this fix added for the 9-branch as well. 

https://github.com/TYPO3/testing-framework/commit/417227d88ad779948346194433042732a45f0539 

Actually as I see it, we don't need the full namespace, as it already has a use statement. 

I'm experience problems with the namespace when using the classes.

**Comment by bmack** [comment]
Can be closed now!
