### ISSUE TITLE
[BUG] Wrong middleware identifier in ext:json_response

### ISSUE THREAD

**Issue by ervaude** [TYPO3/testing-framework#197]
While investigating https://review.typo3.org/c/Packages/TYPO3.CMS/+/65078 I found that the TF uses the nonexisting identifier `typo3/cms-frontend/site-resolver` for its middleware registration. With the linked core patch applied the MW is now not longer on the correct position. Also a middleware cannot be registered after the authentification MW and before the site resolver at the same time, so the configuration has to be changed.

**Comment by lolli42** [comment]
resolved with the patch.
