### ISSUE TITLE
Blind Prophecy Tests using new ProphecyTrait with phpunit

### ISSUE THREAD

**Issue by ohader** [TYPO3/testing-framework#204]
## Description

* origin/reason: https://github.com/sebastianbergmann/phpunit/blob/9.4.0/src/Framework/TestCase.php#L1935-L1944
* impact: phpunit v8 (PHP 7.2) vs phpunit v9 (PHP >=7.3)

Quote from TYPO3 Slack channel by @liayn:

https://typo3.slack.com/archives/C03AM9R17/p1601987304127500

>Could you run the unit test
> \TYPO3\CMS\Core\Tests\Unit\Database\Query\QueryBuilderTest::restrictionsCanStillBeRemovedAfterTheyHaveBeenLimitedToTables()
> locally, but modify the line
> [`SELECT * FROM pages LEFT JOIN t`](https://github.com/TYPO3/TYPO3.CMS/blob/d89063c05055b387cdcbc6df5e5ef374f15b3b5b/typo3/sysext/core/Tests/Unit/Database/Query/QueryBuilderTest.php#L1544) ([rem] modify `tt_content` → `t`)
> in any way?
> Intention: The test should fail of course!
> (but it does not for me locally)

https://typo3.slack.com/archives/C03AM9R17/p1601988025131000

> The testing framework has a major flaw in `\TYPO3\TestingFramework\Core\BaseTestCase`
> it uses the `ProphecyTrait`, which kills the the validation of all prophecies!
> Reasoning: PHPUnit's `TestCase` declares `private $prophet;`
> which is then shadowed (!) by the trait, which redeclares `protected $prophet;` and the method `prophesize(...)`
> Therefore the private prophet never get initalized and consequently the `verifyMockObjects` can never access the prophet

## References

* PR #203 - introducing `ProphecyTrait`
* commit https://github.com/TYPO3/TYPO3.CMS/commit/f767602dc4b3aa6517f0a2d8e9e0b36c8e25d6da - raising testing-framework to `6.4.4` in TYPO3 `master`

**Comment by lolli42** [comment]
We fixed this in core now: Tests that have a dependency to prophecy add the trait on their own.
This is suitable for core v11 which uses phpunit v9.
Extensions compatible with v10 and v11 should restrict phpunit to v8 in their dev dependencies.
