### ISSUE TITLE
Call to protected method TYPO3\CMS\Core\Core\ClassLoadingInformation::getClassLoader()

### ISSUE THREAD

**Issue by FireLizard** [TYPO3/testing-framework#232]
Hi, I'm using the latest Version (6.8.2) of this package but when calling `$this->executeFrontendSubRequest(new InternalRequest())` inside my functional test method it throws the following error:
```
Error : Call to protected method TYPO3\CMS\Core\Core\ClassLoadingInformation::getClassLoader() from context 'TYPO3\TestingFramework\Core\Functional\FunctionalTestCase'
 /opt/project/.Build/vendor/typo3/testing-framework/Classes/Core/Functional/FunctionalTestCase.php:945
 /opt/project/.Build/vendor/typo3/testing-framework/Classes/Core/Functional/FunctionalTestCase.php:895
 /opt/project/Tests/Functional/Controller/ApiControllerTest.php:48
```

As I'm following the hints of the [documentation](https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/Testing/WritingFunctional.html#frontend-tests) I'm not sure if I miss something important.

**Comment by FireLizard** [comment]
Any news on this?

**Comment by lolli42** [comment]
Are you executing tests with v10 core?
executeFrontendSubRequest() does not work with v10, it is only supported with v11 core. Please fall back to executeFrontendRequest() which relies on php process forking in v10.

**Comment by FireLizard** [comment]
Okay, thank you.
My advice is to adjust the composer dependency of this package. Actually its `"typo3/cms-core": "10.*.*@dev || 11.*.*@dev"`
