### ISSUE TITLE
Acceptance tests: Fix page tree navigation - Only search children

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3/testing-framework#243]
### Problem

The typo3/testing-framework acceptance test action \TYPO3\TestingFramework\Core\Acceptance\Helper\AbstractPageTree::openPath tries to to open the first element of the whole TYPO3 backend DOM instead of the first element of the TYPO3 backend page tree only.

### Steps to reproduce
1) Create a page tree with a page name of a TYPO3 backend module, for example "Backend Users".
2) Write an acceptance test which opens the page tree along the path to that page, for example 
```
$pageTree->openPath(["Backend Users"]);
```
3) Run the acceptance test

### Expected

The acceptance test opens the page tree and navigates to the page "Backend Users".

### Actual

The acceptance test fails with
```
[Facebook\WebDriver\Exception\NoSuchElementException] no such element: Unable to locate element: {"method":"css selector","selector":"text.node-name"}
  (Session info: headless chrome=90.0.4430.85) 
```
as the tester gets navigated to the backend module menu item "Backend Users" instead of the page tree node "Backend Users".

### Problems

The problem seems to be two-fold:

1. The implementation assumes that line https://github.com/TYPO3/testing-framework/blob/master/Classes/Core/Acceptance/Helper/AbstractPageTree.php#L87 
   ```
   return $context->findElement(\Facebook\WebDriver\WebDriverBy::xpath('//*[text()=\'' . $nodeText . '\']/..'));
   ```
   searches relative to the $context element, but it searches the whole TYPO3 backend DOM instead.

2. The implementation of descending the page tree in action \TYPO3\TestingFramework\Core\Acceptance\Helper\AbstractPageTree::openPath assumes that the page tree is a nested structure, but it is flat instead.

I do not know how to best descend the page tree along a given path composed by codeception actions, so i am not capable of providing a patch at this moment.

**Comment by lolli42** [comment]
Hey.

This issue is quite old, the page tree navigation works for core and extensions and the described problem has been solved differently in the consuming package already.

I hope its ok to close here for now.
