### ISSUE TITLE
[BUG] HTTP status code is always 200 on executeFrontendSubRequest()

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3/testing-framework#324]
### What are you trying to achieve?

I want to test/assert the HTTP status code of actions in my extension.
Currently is that impossible see: EXT:solr `\ApacheSolrForTypo3\Solr\Tests\Integration\Controller\SearchControllerTest::frontendWillRenderErrorMessageForSolrNotAvailableAction()`
TBD: Links to current implementation will follow.

### What do you get instead?
I marked the test case incomplete.

### How to reproduce the issue?
Try to test any error status code via ForwardResponse.

```
    public function indexAction(): ResponseInterface
    {
        try {
            .... throw some error on this place
        } catch (\Throwable $e) {
            return $this->handleSomethingWrong();
        }
        return $this->htmlResponse();
    } 

    protected function handleSomethingWrong(): ResponseInterface
    {
        $this->logSomethingWrong();
        return new ForwardResponse('somethingWrong');
    }

    public function somethingWrongAction(): ResponseInterface
    {
        return $this->htmlResponse()
            ->withStatus(503, self::STATUS_503_MESSAGE);
    }
```

### Additional information you would like to provide?

**On the real FE request the HTTP status code is as expected, Therefore not opened the issue in TYPO3s forge.**

Following snipped seems to be relevant: 

https://github.com/TYPO3/typo3/blob/6590c5f91f5ddbcf091f26148a2f8aaf727f256c/typo3/sysext/frontend/Classes/Http/RequestHandler.php#L169-L174

### Specify some data of the environment

- TYPO3 testing framework version: 6.15.2
- TYPO3 version: 11.5.5
- TYPO3 installation type: composer
- PHP version: 7.4+
- Web server used + version: Not used
- Operating system: Linux
- Selenium server version: Not used
- Browser driver (chromedriver/geckodriver...) version: Not used
- Browser used + version: Not used

**Comment by lolli42** [comment]
That's actually an issue in core and not in TF:
https://github.com/TYPO3/typo3/blob/11.5/typo3/sysext/extbase/Classes/Core/Bootstrap.php#L209

The code above is the handling of a response back into TSFE - ContentObjectRenderer basically accepts just a string as response from a content object (extbase is a plugin cObj content object). There is no way (yet) to return a full response and let ContentObjectRenderer merge multiple responses.
Therefor, extbase currently sets a header() for the response, which is of course ugly, but can't be handled in a much more elegant way currently.
As such, this extbase response header will not end up in the response object returned to the testing-framework when running a sub-request.

**Comment by lolli42** [comment]
Hey. I hope it's ok to close here for now: This needs to be tackled in core. When this is changed in core, the reponse will have the excepted status code.

**Comment by dkd-kaehm** [comment]
> Hey. I hope it's ok to close here for now: This needs to be tackled in core. When this is changed in core, the reponse will have the excepted status code.

Is there a issue in forge for that?

**Comment by lolli42** [comment]
unsure. go ahead and add one with a good description.
