### ISSUE TITLE
Invalid after key in middleware configuration

### ISSUE THREAD

**Issue by r3h6** [TYPO3/testing-framework#332]
### What are you trying to achieve?

A functional test using a InternalRequest and InternalRequestContext with a frontend user (withFrontendUserId).

### What do you get instead?
```
PHP Fatal error:  Uncaught Error: Call to undefined method stdClass::createUserSession() in /var/www/html/vendor/typo3/testing-framework/Resources/Core/Functional/Extensions/json_response/Classes/Middleware/FrontendUserHandler.php:6
4
Stack trace:
#0 /var/www/html/web/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\JsonResponse\Middleware\FrontendUserHandler->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
```

### How to reproduce the issue?
```php
        $request = (new InternalRequest('http://example.com/'))->withPageId(1);
        $context = (new InternalRequestContext())->withFrontendUserId(2);
        $response = $this->executeFrontendRequest($request, $context);
```
### Additional information you would like to provide?

I guess the problem is in the file: Resources/Core/Functional/Extensions/json_response/Configuration/RequestMiddlewares.php,
There is no middleware called "typo3/cms-frontend/frontend-user-authentication" for the "after" key.

### Specify some data of the environment

- TYPO3 testing framework version: 6
- TYPO3 version: 10.4
- TYPO3 installation type: composer
- PHP version: 7.4

**Comment by lolli42** [comment]
should be solved with the commits.
