### ISSUE TITLE
Import CSV file with "EXT:" prefix doesn't work

### ISSUE THREAD

**Issue by simonschaufi** [TYPO3/testing-framework#358]
### What are you trying to achieve?

Import csv file from an extension

### What do you get instead?

Error message that file is not found

### How to reproduce the issue?

```
$this->importCSVDataSet('EXT:extension/Tests/Functional/Fixtures/fe_users.csv');
```

importing an XML works because the "EXT" prefix is resolved there.

### Specify some data of the environment

- TYPO3 testing framework version: 6.x

**Comment by sbuerk** [comment]
`importCSVDataSet()` operates with an absolute path. I would not start to mix here for a pure TF method with the core resolvings for test setups.

However, you could do that resolving on your own and provide the path:

```php
$this->importCSVDataSet(
  GeneralUtility::getFileAbsFileName('EXT:extension/Tests/Functional/Fixtures/fe_users.csv')
);
```

However this may be only work with package/enabled extension etc and may break in the future.

That's one of the reasons why this TF method works directly with an absolute path and avoiding core method which itselfs may need proper setups being available/done.

E.g. your test is in `EXT:extension/Tests/Functional/SomeFolder/SomeTest.php` you could use:

```php
$this->importCSVDataSet(__DIR__ . '/../Fixtures/fe_users.csv');
```

This also helps, as this is directly resolved by PHPStorm for example and thus jumping to the file is possible. Also automcompleteion is possible that way to avoid "typo" in path and file names during adding this.

I would vote agaist doing/adding the "EXT:" syntax to this method as the befenit do not overweight eventually proplems.

Additionally, often import is used in conjunction with `assertCSVDataSet($fileName)` which itselfs do not support the EXT syntax. This method has been supporting relative paths, but absolute paths are encouraged and relative path resolution for this method is deprecated. Mainly due the same reasons as for the `importCSVDataSet()`.

See: https://github.com/TYPO3/testing-framework/blob/dae5e56b0799cf65420a03d1b87c521c621dd272/Classes/Core/Functional/FunctionalTestCase.php#L706

**Comment by simonschaufi** [comment]
The reason why I come up with this issue is, that it is officially documented to work with importing xml data sets: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Testing/WritingFunctional.html#id6 but doesn't work with csv. I totally understand that the extension needs to be loaded in order for this to work, but at the moment it's just inconsistent. By the way, with the right phpstorm plugins installed you can also click on the "EXT" path ;)

**Comment by simonschaufi** [comment]
> Personally I would leave it the way it is and make the documentation clearer.

I agree.
