### ISSUE TITLE
Doesn't support EXT:static_info_tables_de

### ISSUE THREAD

**Issue by simonschaufi** [TYPO3/testing-framework#359]
### What are you trying to achieve?

Getting translated country names from EXT:static_info_tables_de

### What do you get instead?

Empty string from the field "short_name_de"

### How to reproduce the issue?

1. Activate static_info_tables_de in functional test setup
2. Load a country from the database in extbase
3. Load `$country->shortNameDe` from the country

### Additional information you would like to provide?

The testing framework only considers IMPORT statements but the static_info_tables_de needs to run also UPDATE statements which are ignored.

https://github.com/TYPO3/testing-framework/blob/main/Classes/Core/Testbase.php#L765-L766

Basically this step is missing, what the TYPO3 console does with extension:setupactive:

`\TYPO3\CMS\Extensionmanager\Utility\InstallUtility::processExtensionSetup`

This issue is a bit more complex, as the core doesn't support getting only "UPDATE" statements from the file `ext_tables_static+adt.sql`. Executing the update is actually handled via a slot calling the class.ext_update.php which then runs the SQL update statements. I guess this would be a good feature for the core to support that out of the box. What do you think?

I also created a reference issue for the core: https://forge.typo3.org/issues/97524

### Specify some data of the environment

- TYPO3 testing framework version: 6.x
- TYPO3 version: 10.4

**Comment by lolli42** [comment]
This is the same as #377, is it?

**Comment by sbuerk** [comment]
@lolli42 Nope. #377 is about executing static stuff for all subsequent calls / executions in a TestCase. This is about supporting "UPDATE" statements as static data - currently only "insert" statements are supported. (From CORE and TF as they act similar).

static_info_tables_de uses some quirks for real world installs to (re-)handle the UPDATE statements, which does not work in tests / using TF.

**Comment by lolli42** [comment]
I see. thx.

**Comment by lolli42** [comment]
I had a look at this and I think we should *not* implement support for UPDATE statements from ext_tables_static+adt.sql files into testing-framework:
First, core does not support these, and I added a comment to https://forge.typo3.org/issues/97524 stating that I think it should continue to not support it.
Secondly, you create a dynamic dependency to a moving database state this way. You may not want that. It would be better to provide a .csv file that provides some static rows to be imported within the tests that are under your control.

I'd like to close this issue as rejected.

**Comment by lolli42** [comment]
If you *really* want and need these insert statements to be executed, you should create a helper method in your test case to do whatever magic you need. I just think this shouldn't be established as API of the testing-framework, though.

**Comment by lolli42** [comment]
Also see discussion and decision on #377 which is kinda related to this issue.

**Comment by sbuerk** [comment]
I also think that we  _should not_ implement UPDATE statements support to ext_tables_static+adt.sql, ths ack here with @lolli42.

Tests should provide proper datasets using fixture files (csv).

Ack on reject.

**Comment by lolli42** [comment]
We will deprecate the auto-import of ext_tables_static+adt.sql in TF altogether. See #377 for more information on this. In a transition phase (TF v6), you then might need to truncate the tables in question before importing your own .csv.
