### ISSUE TITLE
Add possibility to simulate Cookies in frontend Requests

### ISSUE THREAD

**Issue by susannemoog** [TYPO3/testing-framework#36]
Original request:

> In a functional test I need to test Extbase controller which depends on Frontend user sessions. The current \TYPO3\CMS\Core\Tests\FunctionalTestCase::getFrontendResponse() doesn't allow me to pass cookies to the Frontend and \TYPO3\CMS\Core\Tests\Functional\Framework\Frontend\Response doesn't allow me to fetch cookies from the Frontend. 

Original Issue:

https://forge.typo3.org/issues/72449

**Comment by lolli42** [comment]
I think this can now be done with the new executeFrontendSubRequest() method.

**Comment by DanielSiepmann** [comment]
I can't see how this should be possible.
https://github.com/TYPO3/testing-framework/blob/6.16.6/Classes/Core/Functional/Framework/Frontend/RequestBootstrap.php#L108 will set cookies to an empty array and I don't see any way to actually set them.

TYPO3 internally does not always use the request properly. And even if it would, there is no way to set cookies on a request, only set the header to set cookies.

**Comment by DanielSiepmann** [comment]
```patch
diff --git a/Classes/Core/Functional/Framework/Frontend/RequestBootstrap.php b/Classes/Core/Functional/Framework/Frontend/RequestBootstrap.php
index f8b2a40..4f4020d 100644
--- a/Classes/Core/Functional/Framework/Frontend/RequestBootstrap.php
+++ b/Classes/Core/Functional/Framework/Frontend/RequestBootstrap.php
@@ -106,6 +106,12 @@ class RequestBootstrap
         }
         // Populating $_COOKIE
         $_COOKIE = [];
+        if ($this->request->hasHeader('Cookie')) {
+            foreach ($this->request->getHeader('Cookie') as $cookie) {
+                [$cookieName, $cookieValue] = explode('=', $cookie, 2);
+                $_COOKIE[$cookieName] = rtrim($cookieValue, ';');
+            }
+        }
 
         // Setting up the server environment
         $_SERVER = [];
```

**Comment by sbuerk** [comment]
Maybe we should get rid of the core places where $_COOKIE is directly read instead of the request object, Extensions should not use the global anymore.

For tests, you can provide it at least in the request object:

```
$request = (new InternalRequest($uri))
  ->withCookieParams([
    'param1' => 'value1',
    'param2' => 123,
    //...
  ]);
$response = $this->executeFrontendSubRequest($request);  
```

**Comment by DanielSiepmann** [comment]
Sure, would be a possible way :) I stumbled upon https://github.com/TYPO3/typo3/blob/11.5/typo3/sysext/core/Classes/Session/UserSessionManager.php#L101 when I wanted to test whether something is persisted when I visit as an anonymous user and add something to my session.

**Comment by DanielSiepmann** [comment]
@sbuerk I don't see how to use your suggestion
> For tests, you can provide it at least in the request object:

The method does not exist.
I'm using 6.16.7 and still don't see how one can test a request containing cookies.
I still need the patch from above.
