### ISSUE TITLE
Allow additional request parameters for frontend requests

### ISSUE THREAD

**Issue by susannemoog** [TYPO3/testing-framework#37]
Original Request:

> In a functional test I need to test Extbase controller which requires various parameters from the client. The current \TYPO3\CMS\Core\Tests\FunctionalTestCase::getFrontendResponse() doesn't allow me to pass those parameters to the Frontend.

Original Issue:
https://forge.typo3.org/issues/72448

**Comment by lolli42** [comment]
I think this can now possible with the new executeFrontendSubRequest() method.
