### ISSUE TITLE
Cache for DependencyInjectionContainer to speedup FunctionalTesting

### ISSUE THREAD

**Issue by sHorst** [TYPO3/testing-framework#371]
When executing Function TestCases Typo3 is generated with every TestCases executed. This will lead to the regeneration (or first generation) of the DependencyInjectionContainer every run. Which takes a big amount of time. 

### Does your feature request relate to a problem?

This will lead to TestCase Times of bigger 10sec.

### Describe the solution you would like

With a cache this could be reduced quite a lot

**Comment by lolli42** [comment]
I hope it's ok to close here. See the PR for details on this.
