### ISSUE TITLE
Enhance assertion of error log entries in functional tests

### ISSUE THREAD

**Issue by susannemoog** [TYPO3/testing-framework#38]
Original Request:

> During the action tests it might happen, that errors occur. To assert expected or unexpected error log entries in the sys_log table, this functionality shall be added to the functional testing framework.
The current implementation just checks the amount of entries, which should be "0" in most cases - which is a bit weak to be considered as complete assertion.

Original Issue:

https://forge.typo3.org/issues/56792

**Comment by lolli42** [comment]
We made the test framework (at least unit & functionals) to not use the core error & exception handler anymore in v11 - exceptions directly bubble up to phpunit. Will close this issue.
