### ISSUE TITLE
Add non-privileged backend user fixture to run tests

### ISSUE THREAD

**Issue by susannemoog** [TYPO3/testing-framework#39]
Original Request:

> The current functional tests are executed by using a admin user in the backend. However, to access further scenarios and access rights, there should some more backend user fixtures that don't have the privileged access to all data.

Original Issue:
https://forge.typo3.org/issues/56069

**Comment by lolli42** [comment]
I'm closing the issue for now: If we want to add non-admin tests runs of for instance the DataHandler tests, this is a much bigger effort than just adding some user to the database. In case anyone starts working on this, we can of course add whatever is needed to the TF, adding some user is just the tip of the iceberg, though.
