### ISSUE TITLE
DependencyInjectionContainer for UnitTests

### ISSUE THREAD

**Issue by bonokburn** [TYPO3/testing-framework#402]
Hi together!

In UnitTests, the dependency-injection container is not available, so all dependencies must be mocked.
Is it possible to provide the DI -container for unitTestCase like in FunctionsTestCase via Bootstrap::init?

Kind regards
Frank

**Comment by sbuerk** [comment]
Nope. And that's how unit-tests are supposed to work. In unit tests you have to create the classes and chains yourself, either real classes or mocked classes. As Unit tests normally have no databases and other needed stuff, most things should be mocked.

However, I do not get the Bootstrap::init for functional tests here. FunctionalTestCase contains a `->getContainer()` to retrieve instances. Not sure about the correct version,
but I think at least with v7 there could be private things retrieved.

DI needs the Symfony DI and the Services.yaml be respected through core and other extensions,
which boils down to a "properly clamped instance" - which is not given in a unit test.

You only need to mock classes which would run things not available in unit tests, like database calls etc.

If you need DI without "mocking" things, you should rely on functional tests.

**Comment by bonokburn** [comment]
Thank you for your quick and detailed reply! Have a good week!
