### ISSUE TITLE
Incompatibility with `Migrations/Code/ClassAliasMap.php` file

### ISSUE THREAD

**Issue by eliashaeussler** [TYPO3/testing-framework#405]
### What are you trying to achieve?

I have a public TYPO3 extension that contains a `Migrations/Code/ClassAliasMap.php` file. This file should be included to build a class alias map.

### What do you get instead?

Whenever such file exists in a TYPO3 extension, running tests with the bootstrap file from TYPO3's testing framework fails with the following message:

```
Error in bootstrap script: RuntimeException:
Cannot set an alias map as the alias loader is not registered!
#0 /var/www/html/public/typo3/sysext/core/Classes/Core/ClassLoadingInformation.php(142): TYPO3\ClassAliasLoader\ClassAliasMap::addAliasMap(Array)
#1 /var/www/html/vendor/typo3/testing-framework/Classes/Core/Testbase.php(648): TYPO3\CMS\Core\Core\ClassLoadingInformation::registerClassLoadingInformation()
#2 /var/www/html/vendor/typo3/testing-framework/Resources/Core/Build/UnitTestsBootstrap.php(81): TYPO3\TestingFramework\Core\Testbase->dumpClassLoadingInformation()
#3 /var/www/html/vendor/typo3/testing-framework/Resources/Core/Build/UnitTestsBootstrap.php(84): PHPUnit\Util\FileLoader::{closure}()
#4 /var/www/html/vendor/phpunit/phpunit/src/Util/FileLoader.php(66): include_once('/var/www/html/v...')
#5 /var/www/html/vendor/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load('/var/www/html/v...')
#6 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(565): PHPUnit\Util\FileLoader::checkAndLoad('./vendor/typo3/...')
#7 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(345): PHPUnit\TextUI\Command->handleBootstrap('./vendor/typo3/...')
#8 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(112): PHPUnit\TextUI\Command->handleArguments(Array)
#9 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#10 /var/www/html/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
#11 /var/www/html/vendor/bin/phpunit(123): include('/var/www/html/v...')
#12 {main}
```

### How to reproduce the issue?

I created a small reproduction repository: https://github.com/eliashaeussler/typo3-class-alias-map-bug-repro

You can find all relevant reproduction steps there.

### Additional information you would like to provide?

No.

### Specify some data of the environment

- TYPO3 testing framework version: 6.16.6
- TYPO3 version: 11.5.16
- TYPO3 installation type: composer
- PHP version: 8.1.8
- Web server used + version: Nginx (via DDEV)
- Operating system: macOS

**Comment by sbuerk** [comment]
Have you tried to add

```json
"typo3/class-alias-loader": {
    "class-alias-maps": [
	    "Migrations/Code/ClassAliasMap.php"
    ]
}
```

to the extension composer.json ? (test extension, not your root json in the demo).

**Comment by eliashaeussler** [comment]
@sbuerk Thanks, it works indeed!

It seems like the `Migrations/Code/ClassAliasMap.php` file is only included if an `ext_emconf.php` is present. Shouldn't the `typo3/class-alias-loader` package (or whoever does this) always check for the presence of a `Migrations/Code/ClassAliasMap.php` file and generate the corresponding autoload files?

**Comment by sbuerk** [comment]
sure, core itself uses it.

**Comment by eliashaeussler** [comment]
Okay, so I guess there should be a notice at https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Autoloading/Background.html#understanding-the-typo3-cms-class-loader pointing to the `extra` section you mentioned above in order to make class alias maps available in Composer mode?

**Comment by sbuerk** [comment]
> The support for class aliases is quite important for TYPO3 CMS, but is not supported by Composer by default. There is a separate Composer package created by Helmut Hummel (available on [GitHub](https://github.com/helhum/class-alias-loader)) which serves as a facade to the Composer class loader and creates not just the information for the prefixes but also the available class aliases for a class and loads them as well.

There is a "hint" .. and the corresponding class-alias-loader has a proper explanation I think. Even with some more insights (I did not read/know before).
However, I'm not deeply into that alias loading thing. 

So, sure - maybe some better hints may be usefull.

**Comment by sbuerk** [comment]
Can we close this here then ?

**Comment by eliashaeussler** [comment]
Thanks for your help.
