### ISSUE TITLE
Call to protected method ClassLoadingInformation::getClassLoader()

### ISSUE THREAD

**Issue by ohader** [TYPO3/testing-framework#437]
> Error : Call to protected method TYPO3\CMS\Core\Core\ClassLoadingInformation::getClassLoader() from context 'TYPO3\TestingFramework\Core\Functional\FunctionalTestCase'

https://github.com/TYPO3/testing-framework/blob/1daf6f57e3ccf6dc84d2404307f06dbfb084284c/Classes/Core/Functional/FunctionalTestCase.php#L1200

In TYPO3 v10 `ClassLoadingInformation::getClassLoader()` is protected and cannot be invoked directly.
In TYPO3 v11 this was fixed with https://review.typo3.org/c/Packages/TYPO3.CMS/+/66708, making mentioned method public, which has not been back-ported to v10.

**Comment by lolli42** [comment]
Yes. This affects branch `6`, which is for core v10 & v11.

TF calls this within `retrieveFrontendSubRequestResult()` which is private and called by public `executeFrontendSubRequest()`. 

Sub requests are only available with core v11 for various reasons (starting with TYPO3_MODE), the method simply can't be used with core v10. The method comment states this: `Note this needs a core v11 and is experimental for extension developers for now.`.

We could throw an exception in case this method is called in a core v10 environment. What do you think?

**Comment by sbuerk** [comment]
+1 for the exception. That is not the first time people trapped into that whole along with v10. Missing changing it on backport or for their extensions with v10 testing.

**Comment by lolli42** [comment]
I think we can close here, this is now guarded better and user receives a proper exception.
