### ISSUE TITLE
AccessibleMock incompatible with phpunit 10

### ISSUE THREAD

**Issue by liayn** [TYPO3/testing-framework#444]
### What are you trying to achieve?

`$this->getAccessibleMock(SomeClass::class)`

Should work.

### What do you get instead?

>Error: Call to undefined method PHPUnit\Framework\MockObject\MockBuilder::setMethods()
> /builds/.../.Build/vendor/typo3/testing-framework/Classes/Core/BaseTestCase.php:59

The method `MockBuilder::setMethods` is gone in phpunit v10.

### Specify some data of the environment

- TYPO3 testing framework version: 7.x-dev aca2f49
- TYPO3 version: 11.5.25
- TYPO3 installation type: composer
- PHP version: 8.2
- phpunit/phpunit (10.0.16)

### related links

https://github.com/sebastianbergmann/phpunit/pull/3687
https://medium.com/bumble-tech/working-with-partial-mocks-in-phpunit-644637e12f84
https://www.drupal.org/project/drupal/issues/3130606

**Comment by lolli42** [comment]
In Fluid standalone, I switched these to setMethods() to onlyMethods() ... guess we should do the same here. The difference is, that onlyMethods() excepts when a methods to mock does not exist, while setMethods() does not. Various core tests that use "dummy" will need to be adapted.

**Comment by liayn** [comment]
The other way around ;-) `setMethods` excepts non-existing methods, whereas the newer `onlyMethods` doesn't.
Those dummy-methods now need `addMethods` to be used.

I guess this is indeed a breaking change for the "accessible proxy" API of the testing framework, unless we do this detection ourselves, but I tend to push this responsibility to the extension author.
