### ISSUE TITLE
prepend `symlink(...)` with @

### ISSUE THREAD

**Issue by DavidBruchmann** [TYPO3/testing-framework#456]
The function symlink throws an error by itself if the target never exists.
As the error is handled individualized and more precise afterwards, the function should be prepended by `@`.

Example:

https://github.com/TYPO3/testing-framework/blob/f55c7154e48c48d956a656fd1e8ebd60d7a515cf/Classes/Core/Testbase.php#L189

**Comment by DavidBruchmann** [comment]
This is the current error-message on cli:

![image](https://user-images.githubusercontent.com/999146/232276951-96da75b4-a235-48cd-8aa4-99e5dabe5dc2.png)

versus the new and desired one:

![image](https://user-images.githubusercontent.com/999146/232277070-35c739bc-82eb-4b7f-803d-dab7a41964b9.png)

**Comment by sbuerk** [comment]
Will work later on tf, therefore creating a small change for this.

Curious why the symlink failed at all. What's your setup / core versions / cms-composerinstallers version ?
