### ISSUE TITLE
Check importCSVDataSet() uid's are unique?

### ISSUE THREAD

**Issue by lolli42** [TYPO3/testing-framework#478]
This might be a good thing to check for:

```
"pages"
,"uid","pid","deleted","t3ver_wsid","t3ver_state","title"
,1,0,0,0,0,"Ok site root"
,1,1,0,0,0,"Ok sub page 1 in live"

```

The second row should be uid=2! This is a common copy&paste pitfall when creating .csv data sets. We may want to check to-import rows for uid uniqueness and otherwise stop since the .csv data is most likely broken? We could assume 'uid' is the first field since this indicates a "common" TCA table, and then track if there is more than one record with same uid to import?

What do you think?

**Comment by sbuerk** [comment]
Not checked, but does mm relation table containing a uid / pk field ?

I'm unsure if we can really make the assumption that the "first" column
is always a uid field (PK).

Beside this, we should consider in this discussion also the "assertCSVDataSet"
counter part as this shares some code paths. #451 descibes additional usecases
in this "case".

If we justify that the "first" colum **must** be the pk / uid field is correct
and safe, such a sanitation and meaningfull error would be nice.

I fear, that we would need to make that more complex and respecting the table
structure information and columns in the csv to decide if we "can" do it.

@lolli42 Let's discuss this along with #451 in a call the next days, what do you think ?

**Comment by lolli42** [comment]
Well, in practice, "uid" *is* the first column - it makes sense to do so. If we assume this, the check would be simple: If the first column is called 'uid', then check if they are unique. For tables that have no uid as first column ("true mm", sys_refindex), simply skip this check. I'm not looking for a fool-proof solution, only something that helps for now for "sane" imports. Checking for uid as first column should thus be enough for the time being and should help finding such import.csv c&p errors rather quickly and for 95% cases.

For asserts: I don't think we need this - the point of asserts.csv is, that they fail if something is wrong. A double-line should thus pop up more easily just because the test fails if the assert.csv file is funny. I think that's good enough.
