### ISSUE TITLE
Testing framework 7.0 needs to depend on symfony/filesystem 5.4+

### ISSUE THREAD

**Issue by andreaswolf** [TYPO3/testing-framework#486]
### What are you trying to achieve?

I'm installing the following combination with minimal requirements (`composer update --prefer-lowest`)

* TYPO3 11.5
* Testing Framework 7.0

### What do you get instead?

I get an error

```
Class 'Symfony\Component\Filesystem\Path' not found
```

### How to reproduce the issue?

Create a Composer project with these requirements:

* `typo3/cms-core: ^11.5`
* `typo3/testing-framework: ^7.0`

### Specify some data of the environment

- TYPO3 testing framework version: 7.0
- TYPO3 version: 11.5
- TYPO3 installation type: Composer
- PHP version: 7.4-8.1
- Web server used + version: n/a
- Operating system: Ubuntu 22.04

**Comment by sbuerk** [comment]
Please use ^7.0.2. This has been addressed with

(main/8) https://github.com/TYPO3/testing-framework/pull/467
(backport/7) https://github.com/TYPO3/testing-framework/pull/468

The exact commit for TF7 is
https://github.com/TYPO3/testing-framework/commit/44d7d208db959c05b830d04779beaddd54fac594

and released with 7.0.2.

No need to require that dependency directly.
