### ISSUE TITLE
BUG: DataSet::parseData() disregards valid content due to empty check

### ISSUE THREAD

**Issue by alexanderschnitzler** [TYPO3/testing-framework#488]
Hi,

in one of my tests I need to import `sys_file_metadata` fixtures. As said table, does not have a `uid` column, my csv looked as such:

```csv
"sys_file_metadata",
,"pid","file"
,0,1
,0,2
```

I realized that my fixtures aren't imported due to an `empty`-check in the parser:

https://github.com/TYPO3/testing-framework/blob/0f64df79ad145ee193f692a2e84e7d6c993d7b5f/Classes/Core/Functional/Framework/DataHandling/DataSet.php#L228

I guess it would be better to compare against an empty string here because `"0"` is considered empty but it is a valid value.

Have a good one.

----------

Related to #451

**Comment by sbuerk** [comment]
That's basically the same spot like reported for the `assertCSVData()`
in #451.

**Comment by lolli42** [comment]
I don't get it: `sys_file_metadata` is a casual TCA table and very well has `uid` column?!

**Comment by alexanderschnitzler** [comment]
Just to complete the picture here. 

Yes, said table has a uid but it's not under test in my case, therefore I don't care what uid the records have. Only interesting column is `file` because I do check relations to files.

However, that's not the point here. A silently failing parser, that drops syntactically correct csv data, is. That's the issue for my customer. Me digging half an hour or more into this for nothing. Please remember, people have to pay our work and as hard TDD is to sell, this is just unnecessary water to the mills for the "we don't pay tests" faction.
