### ISSUE TITLE
SchemaMigrator ServiceNotFoundException

### ISSUE THREAD

**Issue by nhovratov** [TYPO3/testing-framework#498]
Since the last release 8.0.3, I'm getting this error in my functional Tests:

`
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The "TYPO3\CMS\Core\Database\Schema\SchemaMigrator" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.
`
https://github.com/nhovratov/content-blocks/actions/runs/6007213819/job/16292996097

Only happens with TYPO3 v12, main works fine.
PHP: 8.1
DB: Sqlite

**Comment by lolli42** [comment]
This will resolve itself with next v12 patch level release, due to https://review.typo3.org/c/Packages/TYPO3.CMS/+/80530/5/typo3/sysext/core/Configuration/Services.yaml

**Comment by nhovratov** [comment]
Ah, thanks!

**Comment by lolli42** [comment]
I'm sorry, I think we triggered this with the TF patch level tag from yesterday.
Next core v12 patch level is afaik in 2 weeks. Unsure if there is a way to mitigate somehow until then?

**Comment by lolli42** [comment]
We could catch the exception and fall back ... hold on ...

**Comment by lolli42** [comment]
Could you verify if above patch solves the issue? If so, we'd merge and tag next TF v8 soon ...

**Comment by nhovratov** [comment]
> Could you verify if above patch solves the issue? If so, we'd merge and tag next TF v8 soon ...

This solves it!
