### ISSUE TITLE
Add the "testing" keyword to the `composer.json`

### ISSUE THREAD

**Issue by oliverklee** [TYPO3/testing-framework#506]
This causes Composer 2.4 to complain if this package is installed as a production dependency instead of as a development dependency:
https://php.watch/articles/composer-prompt-require-dev-dev-packages

**Comment by lolli42** [comment]
Sounds good. Wanna provide a patch?

**Comment by oliverklee** [comment]
Will do.

**Comment by oliverklee** [comment]
I've just checked: We already have this keyword. So there is nothing left to do here. :smile: Closing.
