### ISSUE TITLE
Setting TypoScript constants/setup within test cases

### ISSUE THREAD

**Issue by saitho** [TYPO3/testing-framework#53]
Concrete example: An image's dimension is set using TypoScript and can be configured in constants. As a developer I want to assure that the image has the correct size defined via the constants (Acceptance Tests), i.e. the setup configuration is correct.

I propose introducing methods like `$I->setTypoScriptSetup('...')` or `$I->setTypoScriptConstant('...')` to enable developers to do that intuitively.

So they might be able to do that:
```
public function checkImageSize() {
    $I->setTypoScriptConstant('plugin.tx_myext.settings.image.width = 200');
    $I->setTypoScriptConstant('plugin.tx_myext.settings.image.height = 100');
    $I->amOnPage('/images');
    $locator = 'img#myTestImage';
    $webdriver = $this->getModule('WebDriver');
    $this->assertEquals($webdriver->grabAttributeFrom($locator, 'width'), 200);
    $this->assertEquals($webdriver->grabAttributeFrom($locator, 'height'), 100);
}
```

Also I'm not too much into TypoScript parsing and conversion into a PHP array, so I don't know if that's easily possible. Pretty sure it doesn't work exactly like in my test example (we might have to set the TS for the test suite...), but I just wanted to drop my suggestion here. :)

**Comment by lolli42** [comment]
Hey. The 'TypoScriptInstruction' construct can inject TS on the fly into the frontend.
I think this solves your request, so I hope it's ok to close here.
