### ISSUE TITLE
Add support for dependencies to TYPO3 Extensions without ext_emconf.php

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3/testing-framework#541]
### Does your feature request relate to a problem?

We removed all our `ext_emconf.php` files when updating from TYPO3 10 LTS to 12 LTS.
This leads to issues like:
```
UnexpectedValueException: The package "e2_ces" depends on "e2/e2-core" which is not present in the system.
```

### Describe the solution you would like

Provide native support for composer only projects with multiple TYPO3 extensions that declare their dependencies on each other (for loading order).

### Optionally, describe alternatives you considered

One could keep ext_emconf.php.

**Comment by DanielSiepmann** [comment]
Probably related to https://github.com/TYPO3/testing-framework/issues/511 and https://github.com/TYPO3/testing-framework/issues/510.

**Comment by websi** [comment]
This is really annoying. Every new release our test fail because this will not be fixed.

It would be really nice if we can use the newest version with extension without "ext_emconf.php".

All our extension has no "ext_emconf.php".

**Comment by DanielSiepmann** [comment]
I already opened a PR which should implement the solution.
I got distracted and couldn't finish my investigation regarding acceptance tests. Feel free to step in and investigate the issue. I hope this is the last missing piece.
