### ISSUE TITLE
Database fails to be dropped

### ISSUE THREAD

**Issue by IchHabRecht** [TYPO3/testing-framework#57]
Given:
- Environment variable with upper case for database name like t3_xtb_DTAGBDEVAL108

Expectation:
- Functional tests are executed without (framework) errors

Actual:
- Functional tests fail with
```
Nimut\TestingFramework\Exception\Exception: Unable to create database with name t3_xtb_DTAGBDEVAL108_ft09fbfa7. This is probably a permission problem. For this instance this could be fixed executing: GRANT ALL ON `t3_xtb_DTAGBDEVAL108_%`.* TO `xxx`@`127.0.0.1`; Original message thrown by database layer: An exception occurred while executing 'CREATE DATABASE t3_xtb_DTAGBDEVAL108_ft09fbfa7':

Can't create database 't3_xtb_dtagbdeval108_ft09fbfa7'; database exists
```

MySQL enforces lower case for database when the database is created. With the change to Doctrine Api the "Drop Database" command is only executed if the given database name is within the available databases. But the comparison is done with the given database name (coming e.g. from ENV) with the returned list of existing databases. The results in searching for t3_xtb_DTAGBDEVAL108_ft09fbfa7 in a list where t3_xtb_dtagbdeval108_ft09fbfa7 exists. Thus the database is never found and never dropped.

See: https://github.com/Nimut/testing-framework/pull/79

**Comment by lolli42** [comment]
Thx. Merged an according patch.
