### ISSUE TITLE
Question about normalizedParams in frontend sub-requests

### ISSUE THREAD

**Issue by nhovratov** [TYPO3/testing-framework#577]
Not sure if this is the correct place to open the issue, however I have a problem migrating Functional Tests from v12 to v13 with the latest version of the testing framework:

I have a test, where I am checking for asset paths in the output HTML. The problem now is, since v13 the paths aren't prefixed anymore. See failing run: https://github.com/nhovratov/content-blocks/actions/runs/9550659756/job/26323141221

While digging deeper, it looks like the property "sitePath" from normalizedParams is different in both versions. This property is used when absRefPrefix is set to "auto", which is always the case in sub requests.

Here some debug outputs:

v12 (sitePath: "/")
![Bildschirmfoto von 2024-06-19 18-42-55](https://github.com/TYPO3/testing-framework/assets/19343425/945a1b32-4dd0-4a1d-ae5f-41d257369927)

v13 (sitePath: ""), siteScript "ttp" also seems cut off.
![Bildschirmfoto 2024-06-19 um 18 38 26](https://github.com/TYPO3/testing-framework/assets/19343425/cbb51d15-0120-49e2-8fae-4c17c6fd0e54)

**Comment by lolli42** [comment]
Hey.

I'm afraid we need some more information here to understand what to do: This smells like a bug in either TF or core, but we're unsure.

Is this still an issue with current v13 main/9 TF?
What do you think where this stems from?
Is there a core functional test that shows this behavior as well? How to reproduce / debug best?

**Comment by nhovratov** [comment]
Here is a functional test showcasing the error with TYPO3/main, TF/main

https://github.com/nhovratov/content-blocks/actions/runs/11259518816/job/31308673475

The exact (!) same setup will work when run from Core monorepo. So it looks like there is some difference.

**Comment by sbuerk** [comment]
I had already a chat with @nhovratov. I know what is involved,
and already did some invetigations - having multiple "solutions"
now available which I need to investigate / analyze against/further:

* core monorepo structure
* usual usage for single extension testing (with changed install root -> ./Build/Web for example)
* usual usage for project/custom monorepo testing
