### ISSUE TITLE
Allow to override database setting in functional test

### ISSUE THREAD

**Issue by IchHabRecht** [TYPO3/testing-framework#58]
As the testing-framework sets ['DB']['Connections']['Default']['initCommands'] from its default configuration, there is currently no way to test without strict mode. If the configuration to override is applied at last, the user is able to define own database configuration.

See: https://github.com/Nimut/testing-framework/pull/76

**Comment by lolli42** [comment]
Is this still an issue we shoud take care of?

**Comment by lolli42** [comment]
Hey. Analyzing FunctionalTestCase, it looks to me as if it should be possible to override db config using '$this->configurationToUseInTestInstance'. I thus assume this issue has been indirectly solved meanwhile, so I hope it's ok to close here for now.
