### ISSUE TITLE
[TASK] BackendEnvironment should not use deprecated config

### ISSUE THREAD

**Issue by thomashohn** [TYPO3/testing-framework#637]
Currently the BackendEnvironment use the 2 following deprecated configurations:

```
$localConfiguration['DB']['Connections']['Default']['tableoptions']['charset'] = 'utf8mb4';
$localConfiguration['DB']['Connections']['Default']['tableoptions']['collate'] = 'utf8mb4_unicode_ci';
```

Instead
```
$localConfiguration['DB']['Connections']['Default']['defaultTableOptions']['charset'] = 'utf8mb4';
$localConfiguration['DB']['Connections']['Default']['defaultTableOptions']['collation'] = 'utf8mb4_unicode_ci';
```
should be used. Since the is a silent migrations this works fine with TYPO3 13 - but will break with 14.
See:
https://forge.typo3.org/issues/105297
and
https://forge.typo3.org/issues/105495

**Comment by sbuerk** [comment]
Solved with https://github.com/TYPO3/testing-framework/pull/640 + https://github.com/TYPO3/testing-framework/pull/633. Closing issue.
