### ISSUE TITLE
v8.2.4: Functional Tests breaking in TYPO3 v12

### ISSUE THREAD

**Issue by saitho** [TYPO3/testing-framework#658]
Hi there,

I have Functional Tests on TYPO3 12 that fail with the latest version v8.2.4.

```
<f:image src="EXT:myext/Resources/Public/images/logo.svg">

TYPO3Fluid\Fluid\Core\ViewHelper\Exception: Unable to render image tag: File /_assets/6666cd76f96956469e7be39d750cc7d9/images/logo.svg does not exist.
```

myext is loaded and symlinked correctly. It worked with v8.2.3.

I think the issue lies somewhere in the path calculation change: https://github.com/TYPO3/testing-framework/commit/93ea4824480b2d76f33be73559ca0b915f84107e

Also passing `false` to composerMode argument in else-branch `SystemEnvironmentBuilder::run()` seems to solve the issue for me...

**Comment by saitho** [comment]
Adding some more background: The extension is a Composer-only extension. Therefore, TYPO3_COMPOSER_MODE is set by autoloader and I can't turn it off, because it's a PHP constant :/

**Comment by sbuerk** [comment]
@saitho Yeah, thanks for reporting. Got already other reports (directly) with other sounding issues, but boils down to the same issue.

Could you try to use a branch if it fixes for you too ?

```bash
composer require --dev typo3/testing-framework:dev-8-stefan-2
```

**Comment by saitho** [comment]
@sbuerk No, it doesn't. Setting `composerMode` to _false_ would work

**Comment by sbuerk** [comment]
Yeah, my bad on redoing it in the other IDE. Force pushed. Can you recheck please? (Running the require command again)

**Comment by sbuerk** [comment]
> @sbuerk Works :)

Thanks. One sanity check against core, than making it ready and releasing it. Thanks for testing and the report :heart:
