### ISSUE TITLE
Wrong path to vendor/autoload.php?

### ISSUE THREAD

**Issue by weberdominik** [TYPO3/testing-framework#68]
In TYPO3 9.2 (composer mode) the path to vendor/autoload.php in TYPO3\TestingFramework\Core\Testbase seems to be wrong (line 575):

> PHPUnit\Framework\Exception:` Fatal error: require(): Failed opening required '/var/www/html/public/typo3/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/vendor/typo3/testing-framework/Classes/Core/Testbase.php on line 575> 

I'm running my functional tests with the following command:
`vendor/bin/phpunit -c vendor/typo3/testing-framework/Resources/Core/Build/FunctionalTests.xml public/typo3conf/ext/my_extension/Tests/Functional/`

As workaround I use a symlink in my testing environment from /public/vendor/ to /vendor/. Should the affected line be changed from
`$classLoader = require rtrim(realpath($instancePath . '/typo3'), '\\/') . '/../vendor/autoload.php';`
to
`$classLoader = require rtrim(realpath($instancePath . '/typo3'), '\\/') . '/../../vendor/autoload.php';`
or is this a configuration error on my side?

**Comment by weberdominik** [comment]
Additionally I get a file not found error when running a functional test for the file:

> /var/www/html/public/typo3temp/var/tests/functional-3343dc7/phpunit`

If I add the phpunit symlink in TYPO3\TestingFramework\Core\TestBase->setUpInstanceCoreLinks everything works as expected.

**Comment by koehnlein** [comment]
Hi, I have the same problem with the wrong autoload path in my TYPO3 8 installation and v 2.0.4 of the testing framework. The problem exists, since I removed `typo3/cms` and switched to composer "subtree split" installation.

Would be great, if this could be handled in both versions: 2 and 3 to be compatible with subtree-split-installations.

**Comment by psychomieze** [comment]
Can you check if https://github.com/TYPO3/testing-framework/pull/103 fixes your issue?

**Comment by IchHabRecht** [comment]
I can tell it's the proper fix for those issues.

**Comment by weberdominik** [comment]
Yes, #103 fixes the issue. Thanks.
